name: loadwolfdev
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=22.1
  - numpy=1.24
  - overrides=7.3
  - prettyprinter=0.18
  - prettytable=3.7
  - pytest=7.2
  - python=3.11
  - scipy=1.10
  - setuptools=67.7
